In [23]:
# Cross Validation Data: mtcrs_for_manymerge.csv

# Import Libraries

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
import os


In [24]:
os.getcwd()

'C:\\Users\\HP\\Downloads\\Batch 93 Day35'

In [25]:
# Load the data set

os.chdir('C:\\Users\\HP\\Downloads\\Batch 93 Day35\\')

In [26]:
os.getcwd()

'C:\\Users\\HP\\Downloads\\Batch 93 Day35'

In [27]:
df=pd.read_csv('mtcars_for_manymerge.csv')
print(df.shape)
print(df)

(21, 7)
                   Cars   mpg  cyl   disp   hp  drat  Feedback
0              MazdaRX4  21.0    6  160.0  110  3.90         1
1          MazdaRX4_WAG  21.0    6  160.0  110  3.90         0
2            Datsun_710  22.8    4  108.0   93  3.85         1
3        Hornet_4_Drive  21.4    6  258.0  110  3.08         1
4     Hornet_Sportabout  18.7    8  360.0  175  3.15         1
5               Valiant  18.1    6  225.0  105  2.76         1
6            Duster_360  14.3    8  360.0  245  3.21         0
7             Merc_240D  24.4    4  146.7   62  3.69         0
8              Merc_230  22.8    4  140.8   95  3.92         1
9              Merc_280  19.2    6  167.6  123  3.92         0
10            Merc_280C  17.8    6  167.6  123  3.92         0
11           Merc_450SE  16.4    8  275.8  180  3.07         0
12           Merc_450SL  17.3    8  275.8  180  3.07         1
13          Merc_450SLC  15.2    8  275.8  180  3.07         1
14   Cadillac_Fleetwood  10.4    8  472.0  205 

In [28]:
# Split the Data Between X and Y

x=df.iloc[:,1:-1].values
print(x)

[[ 21.     6.   160.   110.     3.9 ]
 [ 21.     6.   160.   110.     3.9 ]
 [ 22.8    4.   108.    93.     3.85]
 [ 21.4    6.   258.   110.     3.08]
 [ 18.7    8.   360.   175.     3.15]
 [ 18.1    6.   225.   105.     2.76]
 [ 14.3    8.   360.   245.     3.21]
 [ 24.4    4.   146.7   62.     3.69]
 [ 22.8    4.   140.8   95.     3.92]
 [ 19.2    6.   167.6  123.     3.92]
 [ 17.8    6.   167.6  123.     3.92]
 [ 16.4    8.   275.8  180.     3.07]
 [ 17.3    8.   275.8  180.     3.07]
 [ 15.2    8.   275.8  180.     3.07]
 [ 10.4    8.   472.   205.     2.93]
 [ 10.4    8.   460.   215.     3.  ]
 [ 14.7    8.   440.   230.     3.23]
 [ 32.4    4.    78.7   66.     4.08]
 [ 30.4    4.    75.7   52.     4.93]
 [ 33.9    4.    71.1   65.     4.22]
 [ 21.5    4.   120.1   97.     3.7 ]]


In [29]:
y=df.iloc[:,-1].values
print(y)

[1 0 1 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 0]


In [30]:
# Train test split and model create KNN - split ratio - default 25% without random state
'''execute multiple times and accuracy get change '''

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x_train.shape)
print(x_test.shape)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
metrics.accuracy_score(y_test,y_pred)
 

(15, 5)
(6, 5)


0.3333333333333333

In [31]:
# Train test split and model create KNN - split ratio - default 25% without random state
'''execute multiple times and accuracy get change '''

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x_train.shape)
print(x_test.shape)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
metrics.accuracy_score(y_test,y_pred)
 

(15, 5)
(6, 5)


0.5

In [32]:
# Train test split and model create KNN - split ratio - default 25% without random state
'''execute multiple times and accuracy get change '''

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x_train.shape)
print(x_test.shape)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
metrics.accuracy_score(y_test,y_pred)
 

(15, 5)
(6, 5)


0.3333333333333333

In [33]:
# Train test split and model create KNN - split ratio - default 25% without random state
'''execute multiple times and accuracy get change '''

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x_train.shape)
print(x_test.shape)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
metrics.accuracy_score(y_test,y_pred)
 

(15, 5)
(6, 5)


0.3333333333333333

In [34]:
# Train test split and model create KNN - split ratio - default 25% without random state
'''execute multiple times and accuracy get change '''

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x_train.shape)
print(x_test.shape)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
metrics.accuracy_score(y_test,y_pred)
 

(15, 5)
(6, 5)


0.6666666666666666

In [35]:
# Train test split and model create KNN - split ratio - default 25% without random state
'''execute multiple times and accuracy get change '''

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x_train.shape)
print(x_test.shape)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
metrics.accuracy_score(y_test,y_pred)
 

(15, 5)
(6, 5)


0.5

In [36]:
# Train test split and model create KNN - split ratio - default 25% without random state
'''execute multiple times and accuracy get change '''

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x_train.shape)
print(x_test.shape)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
metrics.accuracy_score(y_test,y_pred)
 

(15, 5)
(6, 5)


0.5

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=10)
print(x_train.shape)
print(x_test.shape)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
metrics.accuracy_score(y_test,y_pred) 

(15, 5)
(6, 5)


0.3333333333333333

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=10)
print(x_train.shape)
print(x_test.shape)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
metrics.accuracy_score(y_test,y_pred) 

(15, 5)
(6, 5)


0.3333333333333333

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=10)
print(x_train.shape)
print(x_test.shape)
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
metrics.accuracy_score(y_test,y_pred) 

(15, 5)
(6, 5)


0.3333333333333333

In [40]:
# Create the KNN model with cross validation - cv=5 using full data set

from sklearn.model_selection import cross_val_score
knn=KNeighborsClassifier(n_neighbors=4)
knn_accuracies=cross_val_score(knn,x,y,cv=5)
print(pd.DataFrame(knn_accuracies)) 

      0
0  0.40
1  0.25
2  0.50
3  0.75
4  0.25


In [41]:
# Accuracy means and standard deviation

print('Mean',knn_accuracies.mean())
print('STD',knn_accuracies.std())

Mean 0.43
STD 0.18601075237738274


In [42]:
# Create the Logistic Regression model with cross validation - cv=5 using full data set

from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logi_accuracies=cross_val_score(logreg,x,y,cv=5)
print(pd.DataFrame(logi_accuracies))

      0
0  0.40
1  0.75
2  0.50
3  0.25
4  0.75


In [43]:
# Accuracy means and standard deviation

print('Mean',logi_accuracies.mean())
print('STD',logi_accuracies.std())

Mean 0.53
STD 0.19646882704388502
